package gui_project;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class ViewGame extends javax.swing.JFrame 
{
    /**
     * Creates new form ViewGame
     */
    public ViewGame() throws IOException 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        Welcome = new javax.swing.JPanel();
        welcomeText = new javax.swing.JLabel();
        play = new javax.swing.JButton();
        quit = new javax.swing.JButton();
        GetDetectiveInfo = new javax.swing.JPanel();
        Note = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        genderTextField = new javax.swing.JTextField();
        ageTextField = new javax.swing.JTextField();
        askNameLabel = new javax.swing.JLabel();
        askGenderLabel = new javax.swing.JLabel();
        askAgeLabel = new javax.swing.JLabel();
        FinishGetInfo = new javax.swing.JButton();
        Story = new javax.swing.JPanel();
        declarePlayerName = new javax.swing.JLabel();
        DetectiveReply = new javax.swing.JPanel();
        NoEnterCompound = new javax.swing.JPanel();
        LogBookKeyPassword = new javax.swing.JPanel();
        LogBookTalks = new javax.swing.JPanel();
        LogBookHints = new javax.swing.JPanel();
        Ground = new javax.swing.JPanel();
        House = new javax.swing.JPanel();
        MaidRoom = new javax.swing.JPanel();
        ButlerRoom = new javax.swing.JPanel();
        WifeRoom = new javax.swing.JPanel();
        WorkingRoom = new javax.swing.JPanel();
        GuessKiller = new javax.swing.JPanel();
        WinOrLose = new javax.swing.JPanel();
        PLayAgain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("Viewer"); // NOI18N
        setSize(ButlerRoom.getPreferredSize());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        Welcome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Welcome.setPreferredSize(new java.awt.Dimension(556, 272));
        Welcome.setVerifyInputWhenFocusTarget(false);

        welcomeText.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        welcomeText.setText("WELCOME TO THE GAME OF DETECTIVE");
        welcomeText.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        play.setText("PLAY");
        play.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                playActionPerformed(evt);
            }
        });

        quit.setText("QUIT");
        quit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                quitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout WelcomeLayout = new javax.swing.GroupLayout(Welcome);
        Welcome.setLayout(WelcomeLayout);
        WelcomeLayout.setHorizontalGroup(
            WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomeLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomeText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(play, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        WelcomeLayout.setVerticalGroup(
            WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomeLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(welcomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(play)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(quit)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jLayeredPane1.add(Welcome, "card13");

        GetDetectiveInfo.setPreferredSize(new java.awt.Dimension(556, 272));

        Note.setText("*Please enter to save your information");

        nameTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                nameTextFieldActionPerformed(evt);
            }
        });

        genderTextField.setToolTipText("");
        genderTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                genderTextFieldActionPerformed(evt);
            }
        });

        ageTextField.setToolTipText("");
        ageTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ageTextFieldActionPerformed(evt);
            }
        });

        askNameLabel.setText("Please enter a name");

        askGenderLabel.setText("Please enter your gender");

        askAgeLabel.setText("Please enter your age");

        FinishGetInfo.setText("Continue");
        FinishGetInfo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                FinishGetInfoActionPerformed(evt);
            }
        });

        GetDetectiveInfo.setVisible(false);

        javax.swing.GroupLayout GetDetectiveInfoLayout = new javax.swing.GroupLayout(GetDetectiveInfo);
        GetDetectiveInfo.setLayout(GetDetectiveInfoLayout);
        GetDetectiveInfoLayout.setHorizontalGroup(
            GetDetectiveInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GetDetectiveInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Note)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FinishGetInfo)
                .addContainerGap())
            .addGroup(GetDetectiveInfoLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(GetDetectiveInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(askNameLabel)
                    .addComponent(askGenderLabel)
                    .addComponent(askAgeLabel))
                .addGap(30, 30, 30)
                .addGroup(GetDetectiveInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(GetDetectiveInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(genderTextField)
                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        GetDetectiveInfoLayout.setVerticalGroup(
            GetDetectiveInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GetDetectiveInfoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(GetDetectiveInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(askNameLabel))
                .addGap(43, 43, 43)
                .addGroup(GetDetectiveInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(askGenderLabel)
                    .addComponent(genderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(GetDetectiveInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(askAgeLabel)
                    .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(GetDetectiveInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FinishGetInfo)
                    .addComponent(Note))
                .addContainerGap())
        );

        jLayeredPane1.add(GetDetectiveInfo, "card14");

        Story.setPreferredSize(new java.awt.Dimension(556, 272));

        declarePlayerName.setText("jLabel1");

        Story.setVisible(false);

        javax.swing.GroupLayout StoryLayout = new javax.swing.GroupLayout(Story);
        Story.setLayout(StoryLayout);
        StoryLayout.setHorizontalGroup(
            StoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StoryLayout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(declarePlayerName)
                .addContainerGap(258, Short.MAX_VALUE))
        );
        StoryLayout.setVerticalGroup(
            StoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StoryLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(declarePlayerName)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        declarePlayerName.getAccessibleContext().setAccessibleName("PlayerName");

        jLayeredPane1.add(Story, "card15");

        DetectiveReply.setPreferredSize(new java.awt.Dimension(556, 272));
        DetectiveReply.setVisible(false);
        jLayeredPane1.add(DetectiveReply, "card16");

        NoEnterCompound.setPreferredSize(new java.awt.Dimension(556, 272));
        NoEnterCompound.setVisible(false);
        jLayeredPane1.add(NoEnterCompound, "card17");
        jLayeredPane1.add(LogBookKeyPassword, "card13");
        jLayeredPane1.add(LogBookTalks, "card13");
        jLayeredPane1.add(LogBookHints, "card13");

        Ground.setPreferredSize(new java.awt.Dimension(556, 272));
        Ground.setVisible(false);
        jLayeredPane1.add(Ground, "card18");

        House.setPreferredSize(new java.awt.Dimension(556, 272));
        House.setVisible(false);
        jLayeredPane1.add(House, "card13");

        MaidRoom.setPreferredSize(new java.awt.Dimension(556, 272));
        MaidRoom.setVisible(false);
        jLayeredPane1.add(MaidRoom, "card14");

        ButlerRoom.setPreferredSize(new java.awt.Dimension(556, 272));
        ButlerRoom.setVisible(false);
        jLayeredPane1.add(ButlerRoom, "card15");

        WifeRoom.setPreferredSize(new java.awt.Dimension(556, 272));
        WifeRoom.setVisible(false);
        jLayeredPane1.add(WifeRoom, "card16");

        WorkingRoom.setPreferredSize(new java.awt.Dimension(556, 272));
        WorkingRoom.setVisible(false);
        jLayeredPane1.add(WorkingRoom, "card17");
        jLayeredPane1.add(GuessKiller, "card13");
        jLayeredPane1.add(WinOrLose, "card13");
        jLayeredPane1.add(PLayAgain, "card13");

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        //TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_quitActionPerformed

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        //TODO add your handling code here:
        changePanel(GetDetectiveInfo);
    }//GEN-LAST:event_playActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
        declarePlayerName.setText(nameTextField.getText());
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void FinishGetInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinishGetInfoActionPerformed
        // TODO add your handling code here:
        changePanel(Story);
    }//GEN-LAST:event_FinishGetInfoActionPerformed

    private void genderTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderTextFieldActionPerformed

    private void ageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTextFieldActionPerformed

    private void changePanel(javax.swing.JPanel nextPanel)
    {
        jLayeredPane1.removeAll();
        jLayeredPane1.add(nextPanel);
        jLayeredPane1.repaint();
        jLayeredPane1.revalidate();
    }
    
    /**
        * @param args the command line arguments
        */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run() 
            {
                try 
                {
                    new ViewGame().setVisible(true);
                } 
                catch (IOException ex) 
                {
                    Logger.getLogger(ViewGame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButlerRoom;
    private javax.swing.JPanel DetectiveReply;
    private javax.swing.JButton FinishGetInfo;
    private javax.swing.JPanel GetDetectiveInfo;
    private javax.swing.JPanel Ground;
    private javax.swing.JPanel GuessKiller;
    private javax.swing.JPanel House;
    private javax.swing.JPanel LogBookHints;
    private javax.swing.JPanel LogBookKeyPassword;
    private javax.swing.JPanel LogBookTalks;
    private javax.swing.JPanel MaidRoom;
    private javax.swing.JPanel NoEnterCompound;
    private javax.swing.JLabel Note;
    private javax.swing.JPanel PLayAgain;
    private javax.swing.JPanel Story;
    private javax.swing.JPanel Welcome;
    private javax.swing.JPanel WifeRoom;
    private javax.swing.JPanel WinOrLose;
    private javax.swing.JPanel WorkingRoom;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JLabel askAgeLabel;
    private javax.swing.JLabel askGenderLabel;
    private javax.swing.JLabel askNameLabel;
    private javax.swing.JLabel declarePlayerName;
    private javax.swing.JTextField genderTextField;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton play;
    private javax.swing.JButton quit;
    private javax.swing.JLabel welcomeText;
    // End of variables declaration//GEN-END:variables

}