package gui_project.View;

import gui_project.ModelController.MainController;
import java.util.Enumeration;
import javax.swing.AbstractButton;

public class GuessKillerView extends javax.swing.JPanel
{

    private final MainController mainCtrl;

    public GuessKillerView(MainController mainCtrl)
    {
        this.mainCtrl = mainCtrl;
        initComponents();
        textField.setEditable(false);
        toggleEndGameBtn(false);
    }

    private void toggleEndGameBtn(boolean state)
    {
        endGame.setVisible(state);
        endGame.setEnabled(state);
    }

    private void disableSelectionButtonGroup()
    {
        Enumeration<AbstractButton> buttons = buttonGroup.getElements();
        while (buttons.hasMoreElements())
        {
            buttons.nextElement().setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup = new javax.swing.ButtonGroup();
        maidRadioBtn = new javax.swing.JRadioButton();
        wifeRadioBtn = new javax.swing.JRadioButton();
        assistantRadioBtn = new javax.swing.JRadioButton();
        daughterRadioBtn = new javax.swing.JRadioButton();
        butlerRadioBtn = new javax.swing.JRadioButton();
        guessBtn = new javax.swing.JButton();
        endGame = new javax.swing.JButton();
        textField = new javax.swing.JTextField();

        setName("GuessKiller"); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup.add(maidRadioBtn);
        maidRadioBtn.setText("Maid");
        add(maidRadioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 250, 30));

        buttonGroup.add(wifeRadioBtn);
        wifeRadioBtn.setText("Wife");
        add(wifeRadioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 250, 24));

        buttonGroup.add(assistantRadioBtn);
        assistantRadioBtn.setText("Assistant");
        add(assistantRadioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 251, -1));

        buttonGroup.add(daughterRadioBtn);
        daughterRadioBtn.setText("Daughter");
        add(daughterRadioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 240, -1));

        buttonGroup.add(butlerRadioBtn);
        butlerRadioBtn.setText("Butler");
        add(butlerRadioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 250, -1));

        guessBtn.setText("Confirm Guess");
        buttonGroup.add(guessBtn);
        guessBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                guessBtnActionPerformed(evt);
            }
        });
        add(guessBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 242, -1));

        endGame.setText("End Game");
        endGame.setToolTipText("");
        endGame.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                endGameActionPerformed(evt);
            }
        });
        add(endGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 110, 30));

        textField.setText("So who do you think murdered our victim?");
        textField.setFocusable(false);
        add(textField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 251, 36));
    }// </editor-fold>//GEN-END:initComponents

    private void guessBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_guessBtnActionPerformed
    {//GEN-HEADEREND:event_guessBtnActionPerformed
        if (daughterRadioBtn.isSelected())
        {
            textField.setText("Awesome! Great work there!!");
        } else
        {
            textField.setText("Too bad you got it wrong");
        }

        disableSelectionButtonGroup();
        toggleEndGameBtn(true);
    }//GEN-LAST:event_guessBtnActionPerformed

    private void endGameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_endGameActionPerformed
    {//GEN-HEADEREND:event_endGameActionPerformed
        mainCtrl.getView().getWindow().dispose();
    }//GEN-LAST:event_endGameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton assistantRadioBtn;
    private javax.swing.JRadioButton butlerRadioBtn;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JRadioButton daughterRadioBtn;
    private javax.swing.JButton endGame;
    private javax.swing.JButton guessBtn;
    private javax.swing.JRadioButton maidRadioBtn;
    private javax.swing.JTextField textField;
    private javax.swing.JRadioButton wifeRadioBtn;
    // End of variables declaration//GEN-END:variables
}
