/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_project.View;

/**
 *
 * @author Angelo
 */
public class GuessKillerPanel extends javax.swing.JPanel
{

    /**
     * Creates new form GuessKillerPanel
     */
    public GuessKillerPanel()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jTextField1 = new javax.swing.JTextField();
        maidRadioBtn = new javax.swing.JRadioButton();
        wifeRadioBtn = new javax.swing.JRadioButton();
        assistantRadioBtn = new javax.swing.JRadioButton();
        daughterRadioBtn = new javax.swing.JRadioButton();
        butlerRadioBtn = new javax.swing.JRadioButton();
        guessBtn = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        maidRadioBtn.setText("Maid");

        wifeRadioBtn.setText("Wife");

        assistantRadioBtn.setText("Assistant");

        daughterRadioBtn.setText("Daughter");

        butlerRadioBtn.setText("Butler");

        guessBtn.setText("Confirm Guess");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butlerRadioBtn)
                    .addComponent(daughterRadioBtn)
                    .addComponent(assistantRadioBtn)
                    .addComponent(wifeRadioBtn)
                    .addComponent(maidRadioBtn)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guessBtn))
                .addContainerGap(849, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(maidRadioBtn)
                .addGap(18, 18, 18)
                .addComponent(wifeRadioBtn)
                .addGap(18, 18, 18)
                .addComponent(assistantRadioBtn)
                .addGap(18, 18, 18)
                .addComponent(daughterRadioBtn)
                .addGap(18, 18, 18)
                .addComponent(butlerRadioBtn)
                .addGap(49, 49, 49)
                .addComponent(guessBtn)
                .addContainerGap(136, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton assistantRadioBtn;
    private javax.swing.JRadioButton butlerRadioBtn;
    private javax.swing.JRadioButton daughterRadioBtn;
    private javax.swing.JButton guessBtn;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton maidRadioBtn;
    private javax.swing.JRadioButton wifeRadioBtn;
    // End of variables declaration//GEN-END:variables
}
