/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_project.View;

import gui_project.ModelController.Detective;
import gui_project.ModelController.MainController;
import gui_project.RPGAppGUI;
import java.io.IOException;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;

/**
 *
 * @author Angelo
 */
public class GuessKillerView extends javax.swing.JPanel
{

    private final MainController mainCtrl;

    /**
     * Creates new form GuessKillerPanel
     */
    public GuessKillerView(MainController mainCtrl)
    {
        this.mainCtrl = mainCtrl;
        initComponents();
        textField.setEditable(false);
    }

    private void setButtonGroupEnabled(boolean state)
    {
        Enumeration<AbstractButton> buttons = buttonGroup.getElements();
        while (buttons.hasMoreElements())
        {
            buttons.nextElement().setEnabled(state);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup = new javax.swing.ButtonGroup();
        maidRadioBtn = new javax.swing.JRadioButton();
        wifeRadioBtn = new javax.swing.JRadioButton();
        assistantRadioBtn = new javax.swing.JRadioButton();
        daughterRadioBtn = new javax.swing.JRadioButton();
        butlerRadioBtn = new javax.swing.JRadioButton();
        guessBtn = new javax.swing.JButton();
        replayLabel = new javax.swing.JLabel();
        yesBtn = new javax.swing.JButton();
        noBtn = new javax.swing.JButton();
        textField = new javax.swing.JTextField();

        setName("GuessKiller"); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup.add(maidRadioBtn);
        maidRadioBtn.setText("Maid");
        add(maidRadioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 78, 250, 30));

        buttonGroup.add(wifeRadioBtn);
        wifeRadioBtn.setText("Wife");
        add(wifeRadioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 108, 250, 24));

        buttonGroup.add(assistantRadioBtn);
        assistantRadioBtn.setText("Assistant");
        add(assistantRadioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 135, 251, -1));

        buttonGroup.add(daughterRadioBtn);
        daughterRadioBtn.setText("Daughter");
        add(daughterRadioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 165, 240, -1));

        buttonGroup.add(butlerRadioBtn);
        butlerRadioBtn.setText("Butler");
        add(butlerRadioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 250, -1));

        guessBtn.setText("Confirm Guess");
        buttonGroup.add(guessBtn);
        guessBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                guessBtnActionPerformed(evt);
            }
        });
        add(guessBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 251, 242, -1));

        replayLabel.setText(" Wanna play again?");
        add(replayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 177, 70));

        yesBtn.setText("Yes");
        yesBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                yesBtnActionPerformed(evt);
            }
        });
        add(yesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 94, 30));

        noBtn.setText("No");
        noBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                noBtnActionPerformed(evt);
            }
        });
        add(noBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 110, 30));

        textField.setText("So who do you think murdered our victim?");
        textField.setFocusable(false);
        add(textField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 17, 251, 36));
    }// </editor-fold>//GEN-END:initComponents

    private void guessBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_guessBtnActionPerformed
    {//GEN-HEADEREND:event_guessBtnActionPerformed
        if (daughterRadioBtn.isSelected())
        {
            textField.setText("Awesome! Great work there!!");
        } else
        {
            textField.setText("Too bad you got it wrong");
        }

        setButtonGroupEnabled(false);
    }//GEN-LAST:event_guessBtnActionPerformed

    private void yesBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_yesBtnActionPerformed
    {//GEN-HEADEREND:event_yesBtnActionPerformed

        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                Detective detective = new Detective();
                try
                {
                    new MainController(detective);
                } catch (IOException ex)
                {
                    Logger.getLogger(RPGAppGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        mainCtrl.getView().getWindow().dispose();
    }//GEN-LAST:event_yesBtnActionPerformed

    private void noBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_noBtnActionPerformed
    {//GEN-HEADEREND:event_noBtnActionPerformed
        mainCtrl.getView().getWindow().dispose();
    }//GEN-LAST:event_noBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton assistantRadioBtn;
    private javax.swing.JRadioButton butlerRadioBtn;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JRadioButton daughterRadioBtn;
    private javax.swing.JButton guessBtn;
    private javax.swing.JRadioButton maidRadioBtn;
    private javax.swing.JButton noBtn;
    private javax.swing.JLabel replayLabel;
    private javax.swing.JTextField textField;
    private javax.swing.JRadioButton wifeRadioBtn;
    private javax.swing.JButton yesBtn;
    // End of variables declaration//GEN-END:variables

}
