package gui_project.View;

import gui_project.ModelController.KeyPasswordController;
import gui_project.ModelController.MainController;
import java.awt.Graphics;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;

public class KeyPasswordQuestionPanel extends javax.swing.JPanel implements ComponentListener
{
    private final MainController mainCtrl;
    private KeyPasswordController keyPasswordCtrl;
    
    /**
     * Creates new form KeyPasswordQuestionPanel
     */
    public KeyPasswordQuestionPanel(MainController mainCtrl, KeyPasswordController keyPasswordCtrl)
    {
        this.mainCtrl = mainCtrl;
        this.keyPasswordCtrl = keyPasswordCtrl;
        
        initComponents();
        setUpTriviaAndQuestionText();
        
        trivialLabel1.setVisible(false);
        trivialLabel2.setVisible(false);
        questionLabel.setVisible(false);
        userInputText.setVisible(false);
        returnButton.setVisible(false);
        resultLabel.setVisible(false);
    }
    
    public void setUpTriviaAndQuestionText()
    {
        trivialLabel1.setText(keyPasswordCtrl.getKeyPassword().getTrivia()[0]);
        trivialLabel2.setText(keyPasswordCtrl.getKeyPassword().getTrivia()[1]);
        
        questionLabel.setText(keyPasswordCtrl.getKeyPassword().getQuestion());
    }

      @Override
    public void componentShown(ComponentEvent e) 
    {
        trivialLabel1.setVisible(false);
        trivialLabel2.setVisible(false);
        questionLabel.setVisible(false);
        userInputText.setVisible(false);
        returnButton.setVisible(false);
        resultLabel.setVisible(false);
        resultLabel.setText("Oops, you are wrong! TRY AGAIN!");
    }

    @Override
    public void componentHidden(ComponentEvent e)
    {
        welcomeLabel.setVisible(true);
        introLabel1.setVisible(true);
        introLabel2.setVisible(true);
        startButton.setVisible(true);
    }
    
    @Override
    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        welcomeLabel = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        introLabel1 = new javax.swing.JLabel();
        introLabel2 = new javax.swing.JLabel();
        trivialLabel1 = new javax.swing.JLabel();
        questionLabel = new javax.swing.JLabel();
        userInputText = new javax.swing.JTextField(20);
        returnButton = new javax.swing.JButton();
        trivialLabel2 = new javax.swing.JLabel();
        resultLabel = new javax.swing.JLabel();

        welcomeLabel.setText("WELCOME TO THE KEY PASSWORD PRIZE!!!!!");

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                startButtonActionPerformed(evt);
            }
        });

        introLabel1.setText("If you correctly answer a question here");

        introLabel2.setText("you will be given a password key that will be helpful somewhere.");

        trivialLabel1.setText("Trivia: ");

        questionLabel.setText("Question: ");

        userInputText.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                userInputTextActionPerformed(evt);
            }
        });

        returnButton.setText("Return the scene");
        returnButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                returnButtonActionPerformed(evt);
            }
        });

        trivialLabel2.setText("Trivia: ");

        resultLabel.setText("Oops, you are wrong! TRY AGAIN!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(253, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(introLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(trivialLabel2)
                            .addComponent(trivialLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(welcomeLabel))
                    .addComponent(introLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(questionLabel)
                    .addComponent(startButton)
                    .addComponent(resultLabel)
                    .addComponent(returnButton)
                    .addComponent(userInputText, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(238, 238, 238))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(trivialLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(trivialLabel2)))
                .addGap(18, 18, 18)
                .addComponent(introLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(introLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(questionLabel)
                .addGap(30, 30, 30)
                .addComponent(userInputText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(startButton)
                .addGap(18, 18, 18)
                .addComponent(resultLabel)
                .addGap(18, 18, 18)
                .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        welcomeLabel.setVisible(false);
        introLabel1.setVisible(false);
        introLabel2.setVisible(false);
        startButton.setVisible(false);
        
        trivialLabel1.setVisible(true);
        trivialLabel2.setVisible(true);
        questionLabel.setVisible(true);
        userInputText.setVisible(true);
        returnButton.setVisible(true);
    }//GEN-LAST:event_startButtonActionPerformed

    private void userInputTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userInputTextActionPerformed
        if(keyPasswordCtrl.checkPassword(userInputText.getText()))
        {
            userInputText.setEnabled(false);
            resultLabel.setText("So true! You can pick the hint now!");
        }
        
        resultLabel.setVisible(true);
    }//GEN-LAST:event_userInputTextActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        userInputText.setText(null);
        
        if(keyPasswordCtrl.getKeyPassword().getName().equals("HeadOffice"))
        {
            mainCtrl.showPanel("House");
        }
        else if(keyPasswordCtrl.getKeyPassword().getName().equals("TailOffice"))
        {
            mainCtrl.showPanel("Ground");
        }
        else if(keyPasswordCtrl.getKeyPassword().getName().equals("HeadDogHouse"))
        {
            mainCtrl.showPanel("WorkingRoom");
        }
        else if(keyPasswordCtrl.getKeyPassword().getName().equals("TailDogHouse"))
        {
            mainCtrl.showPanel("ButlerRoom");
        }
    }//GEN-LAST:event_returnButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel introLabel1;
    private javax.swing.JLabel introLabel2;
    private javax.swing.JLabel questionLabel;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JButton returnButton;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel trivialLabel1;
    private javax.swing.JLabel trivialLabel2;
    private javax.swing.JTextField userInputText;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void componentResized(ComponentEvent e)
    {

    }

    @Override
    public void componentMoved(ComponentEvent e) 
    {
        
    }

  
}
