package gui_project.View;

import gui_project.ModelController.BaseRoomController;
import gui_project.ModelController.KeyPasswordController;
import gui_project.ModelController.LockedArea;
import gui_project.ModelController.MainController;
import java.awt.Graphics;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;

public class KeyPasswordView extends javax.swing.JPanel implements ComponentListener
{
    private final MainController mainCtrl;
    private LockedArea lockedArea;
    
    public KeyPasswordView(MainController mainCtrl, LockedArea lockedArea) 
    {
        initComponents();
        addComponentListener(this);
        this.mainCtrl = mainCtrl;
        this.lockedArea = lockedArea;
    }
    
    @Override
    public void componentResized(ComponentEvent e)
    {

    }

    @Override
    public void componentMoved(ComponentEvent e)
    {
        
    }

    @Override
    public void componentShown(ComponentEvent e) 
    {

    }

    @Override
    public void componentHidden(ComponentEvent e)
    {
        resultLabel.setVisible(false);
        userInputText.setText(null);
    }

    @Override
    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lockStatus = new javax.swing.JLabel();
        enterPassword = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        userInputText = new javax.swing.JTextField();
        resultLabel = new javax.swing.JLabel();

        setName("EnterKeyPassword"); // NOI18N

        lockStatus.setText("This door is locked!");
        lockStatus.setName("lockStatus"); // NOI18N

        enterPassword.setText("Enter a password to unlock the door");
        enterPassword.setName("EnterPassword"); // NOI18N

        backButton.setText("Back");
        backButton.setName("submitPasswordButton"); // NOI18N
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        userInputText.setName("UserInputText"); // NOI18N
        userInputText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userInputTextActionPerformed(evt);
            }
        });

        resultLabel.setText("Result");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(lockStatus)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(173, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(enterPassword)
                        .addGap(164, 164, 164))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(userInputText, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(resultLabel)
                        .addGap(288, 288, 288))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addGap(277, 277, 277))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lockStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterPassword)
                .addGap(51, 51, 51)
                .addComponent(userInputText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(resultLabel)
                .addGap(33, 33, 33)
                .addComponent(backButton)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        lockStatus.getAccessibleContext().setAccessibleName("");
        resultLabel.setVisible(false);
    }// </editor-fold>//GEN-END:initComponents

    private void userInputTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userInputTextActionPerformed
        String userInput = userInputText.getText();
        
        //todo: check password
        if(userInput.equals(lockedArea.getPassword()))
        {
            resultLabel.setText("You are correct! DOOR OPEN");
                        
        }
        else
        {
            resultLabel.setText("You are wrong! TRY AGAIN");
        }
        
        resultLabel.setVisible(true);
    }//GEN-LAST:event_userInputTextActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        //todo: check password
            //Correct -> Mess appears -> unlocked ItemBlock -> Close panel
            //Wrong -> Mess appears -> Close panel
        if(lockedArea.getName().equals("DogHouseLock"))
        {
            mainCtrl.showPanel("Ground");
        }
        else 
        {
            mainCtrl.showPanel("WorkingRoom");
        }
        
    }//GEN-LAST:event_backButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel enterPassword;
    private javax.swing.JLabel lockStatus;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JTextField userInputText;
    // End of variables declaration//GEN-END:variables

}
