package gui_project.View;

import gui_project.ModelController.MainController;
import gui_project.ModelController.NPCVictimController;
import java.awt.Font;

public class NPCVictimView extends javax.swing.JPanel 
{
    private MainController mainCtrl;
    private NPCVictimController victimCtrl;
    
    public NPCVictimView(MainController mainCtrl, NPCVictimController victimCtrl) 
    {
        this.mainCtrl = mainCtrl;
        this.victimCtrl = victimCtrl;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        victimName = new javax.swing.JLabel();
        victimRole = new javax.swing.JLabel();
        victimAge = new javax.swing.JLabel();
        victimScene = new javax.swing.JLabel();
        victimInjury = new javax.swing.JLabel();
        enterCcompound = new javax.swing.JButton();
        victimInforLabel = new javax.swing.JLabel();

        setName("Victim"); // NOI18N

        victimName.setText(victimCtrl.getVictim().getName());

        victimRole.setText(victimCtrl.getVictim().getRole());

        victimAge.setText(victimCtrl.getVictim().getAge().toString());

        victimScene.setText("Scene: " + victimCtrl.getVictim().getScene());

        victimInjury.setText(victimCtrl.getVictim().getInjuries());

        enterCcompound.setText("Enter the house");
        enterCcompound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterCcompoundActionPerformed(evt);
            }
        });

        victimInforLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        victimInforLabel.setText("VICTIM INFORMATION");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(victimName)
                    .addComponent(victimInjury)
                    .addComponent(victimRole)
                    .addComponent(victimAge)
                    .addComponent(victimScene))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(239, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(enterCcompound)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(victimInforLabel)
                        .addGap(237, 237, 237))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(victimInforLabel)
                .addGap(18, 18, 18)
                .addComponent(victimName)
                .addGap(41, 41, 41)
                .addComponent(victimRole)
                .addGap(40, 40, 40)
                .addComponent(victimAge)
                .addGap(43, 43, 43)
                .addComponent(victimScene)
                .addGap(46, 46, 46)
                .addComponent(victimInjury)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterCcompound)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        victimInforLabel.setFont(new Font("Serif", Font.BOLD, 16));
    }// </editor-fold>//GEN-END:initComponents

    private void enterCcompoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterCcompoundActionPerformed
        mainCtrl.showPanel("Ground");
    }//GEN-LAST:event_enterCcompoundActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enterCcompound;
    private javax.swing.JLabel victimAge;
    private javax.swing.JLabel victimInforLabel;
    private javax.swing.JLabel victimInjury;
    private javax.swing.JLabel victimName;
    private javax.swing.JLabel victimRole;
    private javax.swing.JLabel victimScene;
    // End of variables declaration//GEN-END:variables
}
