package gui_project.View;

import gui_project.ModelController.LockedAreaController;
import gui_project.ModelController.MainController;
import java.awt.Graphics;

public class PasswordInputPanel extends javax.swing.JPanel
{
    private final MainController mainCtrl;
    private LockedAreaController lockedAreaCtrl;
    
    public PasswordInputPanel(MainController mainCtrl, LockedAreaController lockedAreaCtrl) 
    {
        initComponents();
        this.mainCtrl = mainCtrl;
        this.lockedAreaCtrl = lockedAreaCtrl;
    }

    @Override
    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lockStatus = new javax.swing.JLabel();
        enterPassword = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        userInputText = new javax.swing.JTextField();
        resultLabel = new javax.swing.JLabel();

        setName("EnterKeyPassword"); // NOI18N

        lockStatus.setText("THIS DOOR IS LOCKED");
        lockStatus.setName("lockStatus"); // NOI18N

        enterPassword.setText("Enter a password to unlock the door");
        enterPassword.setName("EnterPassword"); // NOI18N

        backButton.setText("Back");
        backButton.setName("submitPasswordButton"); // NOI18N
        backButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                backButtonActionPerformed(evt);
            }
        });

        userInputText.setName("UserInputText"); // NOI18N
        userInputText.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                userInputTextActionPerformed(evt);
            }
        });

        resultLabel.setText("Result");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButton)
                    .addComponent(resultLabel)
                    .addComponent(lockStatus)
                    .addComponent(enterPassword)
                    .addComponent(userInputText, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(261, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(lockStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enterPassword)
                .addGap(26, 26, 26)
                .addComponent(userInputText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultLabel)
                .addGap(11, 11, 11)
                .addComponent(backButton)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        lockStatus.getAccessibleContext().setAccessibleName("");
        resultLabel.setVisible(false);
    }// </editor-fold>//GEN-END:initComponents

    //todo: bring this to Controller
    private void userInputTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userInputTextActionPerformed
        String userInput = userInputText.getText();
        
        //todo: check password        
        if(userInput.equals(lockedAreaCtrl.getLockedArea().getPassword()))
        {
            resultLabel.setText("You are correct! DOOR OPEN");
            lockedAreaCtrl.disableLockedArea();
        }
        else
        {
            resultLabel.setText("You are wrong! TRY AGAIN");
        }
        
        resultLabel.setVisible(true);
    }//GEN-LAST:event_userInputTextActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        //todo: check password
            //Correct -> Mess appears -> unlocked ItemBlock -> Close panel
            //Wrong -> Mess appears -> Close panel
        resultLabel.setVisible(false);
        userInputText.setText(null);
        
        if(lockedAreaCtrl.getLockedArea().getName().equals("DogHouseLock"))
        {
            mainCtrl.showPanel("Ground");
        }
        else 
        {
            mainCtrl.showPanel("WorkingRoom");
        }
        
    }//GEN-LAST:event_backButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel enterPassword;
    private javax.swing.JLabel lockStatus;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JTextField userInputText;
    // End of variables declaration//GEN-END:variables

}
