package gui_project.View;

import gui_project.ModelController.MainController;
import gui_project.ModelController.PlayerInfoController;

public class PlayerInfoView extends javax.swing.JPanel
{

    MainController mainCtrl;
    PlayerInfoController playerInfoCtrl;
    boolean nameChecked, ageChecked, genderChecked;

    public PlayerInfoView(MainController mainCtrl, PlayerInfoController playerInforCtrl)
    {
        this.mainCtrl = mainCtrl;
        this.playerInfoCtrl = playerInforCtrl;

        initComponents();
        invalidLabel.setVisible(false);
        yesLabel1.setVisible(false);
        yesLabel2.setVisible(false);
        yesLabel3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        Note = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        genderTextField = new javax.swing.JTextField();
        ageTextField = new javax.swing.JTextField();
        askNameLabel = new javax.swing.JLabel();
        askGenderLabel = new javax.swing.JLabel();
        askAgeLabel = new javax.swing.JLabel();
        continueButton = new javax.swing.JButton();
        invalidLabel = new javax.swing.JLabel();
        yesLabel1 = new javax.swing.JLabel();
        yesLabel2 = new javax.swing.JLabel();
        yesLabel3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setName("PlayerInfor"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 500));

        Note.setText("*Press enter to save your information");

        nameTextField.setName(""); // NOI18N
        nameTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                nameTextFieldActionPerformed(evt);
            }
        });

        genderTextField.setToolTipText("");
        genderTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                genderTextFieldActionPerformed(evt);
            }
        });

        ageTextField.setToolTipText("");
        ageTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ageTextFieldActionPerformed(evt);
            }
        });

        askNameLabel.setText("Please enter a name");

        askGenderLabel.setText("Please enter a gender");

        askAgeLabel.setText("Please enter an age");

        continueButton.setText("Continue");
        continueButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                continueButtonActionPerformed(evt);
            }
        });

        invalidLabel.setText("Invalid input, please enter again");
        invalidLabel.setName("invalidLabel"); // NOI18N

        yesLabel1.setText("Y");

        yesLabel2.setText("Y");

        yesLabel3.setText("Y");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(askGenderLabel)
                            .addComponent(invalidLabel)
                            .addComponent(askAgeLabel)
                            .addComponent(continueButton)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(askNameLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(genderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(yesLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(yesLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(yesLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(Note)))
                .addGap(198, 198, 198))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(Note, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yesLabel1)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(genderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(yesLabel2)))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(yesLabel3))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(askNameLabel)
                        .addGap(43, 43, 43)
                        .addComponent(askGenderLabel)
                        .addGap(50, 50, 50)
                        .addComponent(askAgeLabel)
                        .addGap(26, 26, 26)
                        .addComponent(invalidLabel)
                        .addGap(28, 28, 28)
                        .addComponent(continueButton)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void genderTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderTextFieldActionPerformed

        //Check if the input is valid
        if (genderTextField.getText().equalsIgnoreCase("M")
                || genderTextField.getText().equalsIgnoreCase("F"))
        {
            playerInfoCtrl.setPlayerGender(genderTextField.getText().charAt(0));
            invalidLabel.setVisible(false);
            yesLabel2.setVisible(true);
            genderChecked = true;
        } else
        {
            genderChecked = false;
            invalidLabel.setText("Invalid gender, please enter M/F");
            invalidLabel.setVisible(true);
            yesLabel2.setVisible(false);
        }
    }//GEN-LAST:event_genderTextFieldActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed

        //Check if the input is valid
        if (!nameTextField.getText().equals("") && nameTextField.getText() != null
                && nameTextField.getText().matches("^[ a-zA-Z]*$"))
        {
            playerInfoCtrl.setPlayerName(nameTextField.getText());
            invalidLabel.setVisible(false);
            yesLabel1.setVisible(true);
            nameChecked = true;
        } else
        {
            nameChecked = false;
            invalidLabel.setText("Invalid name, please enter characters only");
            invalidLabel.setVisible(true);
            yesLabel1.setVisible(false);
        }
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
        if (nameChecked && genderChecked && ageChecked)
        {
            mainCtrl.showPanel("Story");
            invalidLabel.setVisible(false);
            playerInfoCtrl.savePlayerInfo();

        } else
        {
            invalidLabel.setText("Please make sure that name, gender, and age has been filled/valid");
            invalidLabel.setVisible(true);
        }
    }//GEN-LAST:event_continueButtonActionPerformed

    private void ageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTextFieldActionPerformed

        //Check if the input is valid
        boolean ageValid = false;
        if (!ageTextField.getText().equals("") && ageTextField.getText() != null
                && ageTextField.getText().matches("[0-9]+"))
        {
            int age = Integer.parseInt(ageTextField.getText());
            if (age >= 1 && age <= 150)
            {
                playerInfoCtrl.setPlayerAge(age);
                invalidLabel.setVisible(false);
                yesLabel3.setVisible(true);
                ageChecked = true;
                ageValid = true;
            }
        }
        if (!ageValid)
        {
            ageChecked = false;
            invalidLabel.setText("Invalid age, the correct range is from 1 to 150");
            invalidLabel.setVisible(true);
            yesLabel3.setVisible(false);
        }
    }//GEN-LAST:event_ageTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Note;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JLabel askAgeLabel;
    private javax.swing.JLabel askGenderLabel;
    private javax.swing.JLabel askNameLabel;
    private javax.swing.JButton continueButton;
    private javax.swing.JTextField genderTextField;
    private javax.swing.JLabel invalidLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel yesLabel1;
    private javax.swing.JLabel yesLabel2;
    private javax.swing.JLabel yesLabel3;
    // End of variables declaration//GEN-END:variables

}
