/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_project.View;

import gui_project.ModelController.BaseModel;
import gui_project.ModelController.DetectiveController;
import gui_project.ModelController.MainController;
import gui_project.ModelController.NPCController;
import gui_project.ModelController.RoomGroundController;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import javax.swing.ImageIcon;
import gui_project.ModelController.Hint;
import gui_project.ModelController.NPC;
import gui_project.ModelController.BaseObserver;
import gui_project.ModelController.HintController;
import gui_project.ModelController.ItemBlockController;
import gui_project.ModelController.LockedAreaController;

/**
 *
 * @author Angelo
 */
public class RoomGroundView extends javax.swing.JPanel implements
        ComponentListener, BaseObserver
{
    private final DetectiveController detectiveCtrl;
    private final MainController mainCtrl;
    private final NPCController butlerCtrl;
    private final RoomGroundController roomCtrl;
    private Rectangle dogHouse;

    /**
     * Creates new form RoomView
     */
    public RoomGroundView(MainController mainCtrl,
            DetectiveController detectiveCtrl,
            NPCController butlerCtrl,
            RoomGroundController roomCtrl)
    {
        this.mainCtrl = mainCtrl;
        this.detectiveCtrl = detectiveCtrl;
        this.butlerCtrl = butlerCtrl;
        this.roomCtrl = roomCtrl;

        initComponents();
        addComponentListener(this);
        setFocusable(true);
    }

    public Rectangle getBound()
    {
        return new Rectangle(10, 15,
                this.getSize().width - 30, this.getSize().height - 30);
    }

    public Image getHouseImage()
    {
        ImageIcon imageIcon = new ImageIcon("./Images/House.png");
        Image image = imageIcon.getImage();
        Image changeImageSize = image.getScaledInstance(200, 200, 4);
        imageIcon = new ImageIcon(changeImageSize);
        image = imageIcon.getImage();

        return image;
    }

    @Override
    public void update(BaseModel model)
    {
        if (model instanceof NPC)
        {
            gameTextArea.setText(((NPC) model).getSpokenLine());
        }
        else if (model instanceof Hint)
        {
            gameTextArea.setText(((Hint) model).getMessage());
        }
    }

    @Override
    public void componentShown(ComponentEvent e)
    {
        /*we can use this method to setup the view before it is shown in the main panel
         *the requestFocus is the one used to keep the detective moving
         */
        roomCtrl.getItemBlockCtrls().forEach(i ->
        {
            i.getItemBlock().registerObserver(this);
        });

        requestFocusInWindow();
    }

    @Override
    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g;
        
        detectiveCtrl.draw(g2);
        g2.draw(getBound());
        g2.drawImage(getHouseImage(), 276, 83, null);

        roomCtrl.getItemBlockCtrls().forEach(itemBlockCtrl ->
        {
            if (itemBlockCtrl instanceof NPCController)
            {
                NPCController npc = (NPCController) itemBlockCtrl;
                npc.draw(g2);
            } 
            else if (itemBlockCtrl instanceof HintController)
            {
                HintController hint = (HintController) itemBlockCtrl;
                hint.draw(g2);
            }
            else if(itemBlockCtrl instanceof LockedAreaController)
            {
                LockedAreaController areaLocked = (LockedAreaController) itemBlockCtrl;
                areaLocked.draw(g2);
                
                dogHouse = areaLocked.getView().getBound();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roomName = new javax.swing.JLabel();
        doorHouse = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gameTextArea = new javax.swing.JTextArea();

        setName("Ground"); // NOI18N
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roomName.setText("Ground");
        add(roomName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        doorHouse.setText("_____");
        doorHouse.setName("DoorHouse"); // NOI18N
        add(doorHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, -1, -1));

        gameTextArea.setColumns(20);
        gameTextArea.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        gameTextArea.setRows(5);
        gameTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(gameTextArea);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 740, 120));
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_formKeyPressed
    {//GEN-HEADEREND:event_formKeyPressed
        //Collision check
        roomCtrl.checkCollisions(evt.getKeyCode(), roomCtrl.getItemBlockCtrls(),
                detectiveCtrl, getBound());

        repaint();
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_formKeyReleased
    {//GEN-HEADEREND:event_formKeyReleased
        detectiveCtrl.keyReleased(evt);

        //check doorHouse collision
        if (detectiveCtrl.getView().getBound().intersects(doorHouse.getBounds()))
        {
            mainCtrl.showPanel("House");
            detectiveCtrl.updateGroundHouseLocation();
            System.out.println("Print House");
        }
        //check lockedArea collision
        else if(detectiveCtrl.getView().getBound().intersects(dogHouse))
        {
            mainCtrl.showPanel("DogHouseLock");
        }

        repaint();
    }//GEN-LAST:event_formKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel doorHouse;
    private javax.swing.JTextArea gameTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel roomName;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentHidden(ComponentEvent e)
    {
       
    }

    @Override
    public void componentResized(ComponentEvent e)
    {

    }

    @Override
    public void componentMoved(ComponentEvent e)
    {

    }
}
