/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_project.View;

import gui_project.ModelController.DetectiveController;
import gui_project.ModelController.MainController;
import gui_project.ModelController.NPCController;
import gui_project.ModelController.RoomButlerController;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;

/**
 *
 * @author pc
 */
public class RoomButlerView extends javax.swing.JPanel implements ComponentListener
{
    private final MainController mainCtrl;
    private final DetectiveController detectiveCtrl;
    private final NPCController assistantCtrl;
    private final RoomButlerController roomCtrl;

    /**
     * Creates new form RoomView
     */
    public RoomButlerView(MainController mainCtrl,
            DetectiveController detectiveCtrl,
            NPCController assistantCtrl,
            RoomButlerController roomCtrl)
    {     
        this.mainCtrl = mainCtrl;
        this.detectiveCtrl = detectiveCtrl;
        this.assistantCtrl = assistantCtrl;
        this.roomCtrl = roomCtrl;
        
        initComponents();
        addComponentListener(this);
        setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        houseDoor = new javax.swing.JLabel();

        setName("ButlerRoom"); // NOI18N
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jLabel1.setText("ButlerRoom");

        houseDoor.setText("*");
        houseDoor.setFocusCycleRoot(true);
        houseDoor.setName("MaidRoomDoor"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(houseDoor)))
                .addContainerGap(299, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(houseDoor)
                .addContainerGap(350, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        
        detectiveCtrl.keyPressed(evt);
        repaint();
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
        
        detectiveCtrl.keyReleased(evt);
        
        if(detectiveCtrl.getView().getBound().intersects(houseDoor.getBounds()))
        {
            mainCtrl.showPanel("House");
        }
        
        repaint();
    }//GEN-LAST:event_formKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel houseDoor;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void componentResized(ComponentEvent e) {

    }

    @Override
    public void componentMoved(ComponentEvent e) {

    }

    @Override
    public void componentShown(ComponentEvent e) {
        requestFocusInWindow();
    }

    @Override
    public void componentHidden(ComponentEvent e) {

    }
        
    @Override
    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        
        Graphics2D g2 = (Graphics2D) g;
        
        detectiveCtrl.draw(g2);
        assistantCtrl.draw(g2);
    }
}
