/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_project.View;

import gui_project.ModelController.BaseModel;
import gui_project.ModelController.DetectiveController;
import gui_project.ModelController.MainController;
import gui_project.ModelController.NPCController;
import gui_project.ModelController.RoomGroundController;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import javax.swing.ImageIcon;
import gui_project.ModelController.Hint;
import gui_project.ModelController.NPC;
import gui_project.ModelController.BaseObserver;
import gui_project.ModelController.HintController;

/**
 *
 * @author Angelo
 */
public class RoomGroundView extends javax.swing.JPanel implements
        ComponentListener, BaseObserver
{

    private final MainController mainCtrl;
    private final DetectiveController detectiveCtrl;
    private final NPCController butlerCtrl;
    private final RoomGroundController roomCtrl;

    /**
     * Creates new form RoomView
     */
    public RoomGroundView(MainController mainCtrl,
            DetectiveController detectiveCtrl,
            NPCController butlerCtrl,
            RoomGroundController roomCtrl)
    {
        this.mainCtrl = mainCtrl;
        this.detectiveCtrl = detectiveCtrl;
        this.butlerCtrl = butlerCtrl;
        this.roomCtrl = roomCtrl;

        initComponents();
        addComponentListener(this);
        setFocusable(true);
    }

    public Rectangle getBound()
    {
        return new Rectangle(10, 15,
                this.getSize().width - 30, this.getSize().height - 30);
    }

    public Image getHouseImage()
    {
        ImageIcon imageIcon = new ImageIcon("./Images/House.png");
        Image image = imageIcon.getImage();
        Image changeImageSize = image.getScaledInstance(200, 200, 4);
        imageIcon = new ImageIcon(changeImageSize);
        image = imageIcon.getImage();

        return image;
    }

    @Override
    public void update(BaseModel model)
    {
        if (model instanceof NPC)
        {
            gameTextArea.setText(((NPC) model).getSpokenLine());
        }
        else if (model instanceof Hint)
        {
            gameTextArea.setText(((Hint) model).getMessage());
        }
        mainCtrl.updateConversationLevel();
    }

    @Override
    public void componentShown(ComponentEvent e)
    {
        /*we can use this method to setup the view before it is shown in the main panel
        *the requestFocus is the one used to keep the detective moving
         */
        //this registering feels wrong on every component show..anywayyys i'll just leave it here
        //as we can't do it on instantiation
        roomCtrl.getItemBlockCtrls().forEach(i ->
        {
            i.getItemBlock().registerObserver(this);
        });

        requestFocusInWindow();
    }

    @Override
    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);

        Graphics2D g2 = (Graphics2D) g;
        detectiveCtrl.draw(g2);

        roomCtrl.getItemBlockCtrls().forEach(itemBlockCtrl ->
        {
            if (itemBlockCtrl instanceof NPCController)
            {
                NPCController npc = (NPCController) itemBlockCtrl;
                npc.draw(g2);
            } 
            else if (itemBlockCtrl instanceof HintController)
            {
                HintController hint = (HintController) itemBlockCtrl;
                hint.draw(g2);
            }
        });
        g2.draw(getBound());
        g2.drawImage(getHouseImage(), 276, 83, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        roomName = new javax.swing.JLabel();
        doorHouse = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gameTextArea = new javax.swing.JTextArea();

        setName("Ground"); // NOI18N
        addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                formKeyReleased(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roomName.setText("Ground");
        add(roomName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        doorHouse.setText("_____");
        doorHouse.setName("DoorHouse"); // NOI18N
        add(doorHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, -1, -1));

        gameTextArea.setColumns(20);
        gameTextArea.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        gameTextArea.setRows(5);
        gameTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(gameTextArea);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 800, 90));
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_formKeyPressed
    {//GEN-HEADEREND:event_formKeyPressed
        //I think we can check for the boundaries here -- if going outside the bounds
        //we wont call the keyPress

        //check house collision
        roomCtrl.checkCollisions(evt.getKeyCode(), roomCtrl.getItemBlockCtrls(),
                detectiveCtrl, getBound());

        repaint();
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_formKeyReleased
    {//GEN-HEADEREND:event_formKeyReleased
        //I think we can check for the boundaries here -- if going outside the bounds
        //we wont call the keyPress

        detectiveCtrl.keyReleased(evt);

        //check doorHouse collision
        if (detectiveCtrl.getView().getBound().intersects(doorHouse.getBounds()))
        {
            mainCtrl.showPanel("House");
            detectiveCtrl.updateGroundHouseLocation();
            System.out.println("Print House");
        }

        repaint();
    }//GEN-LAST:event_formKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel doorHouse;
    private javax.swing.JTextArea gameTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel roomName;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentHidden(ComponentEvent e)
    {
        /*
            I found it is hard to save detective location here, 
            as the method in every view is invoked from bottom to the top.
            Eg. MainController adds GroundCtrl first, then HouseCtrl, then ButlerCtrl.
            However, componentHidden() in ButlerCtrl was invoked at the beginning,
            then HouseCtrl, then GroundCtrl, even before the player can move. 
            I mean I need to initialise Detective previousLocation to fit the order.
            
            Thus, I created a method updateGroundHouseLocation() to save current location 
            in DetectiveController just for now. We might change/move it in the future.
         */
    }

    @Override
    public void componentResized(ComponentEvent e)
    {

    }

    @Override
    public void componentMoved(ComponentEvent e)
    {

    }
}
