/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_project.View;

import gui_project.ModelController.DetectiveController;
import gui_project.ModelController.MainController;
import gui_project.ModelController.NPCController;
import gui_project.ModelController.RoomMaidController;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;

/**
 *
 * @author pc
 */
public class RoomMaidView extends javax.swing.JPanel implements ComponentListener
{
    private final MainController mainCtrl;
    private final DetectiveController detectiveCtrl;
    private final NPCController maidCtrl;
    private final RoomMaidController roomCtrl;

    /**
     * Creates new form RoomTwoView
     */
    public RoomMaidView(MainController mainCtrl,
            DetectiveController detectiveCtrl,
            NPCController maidCtrl,
            RoomMaidController roomCtrl)
    {
        this.mainCtrl = mainCtrl;
        this.detectiveCtrl = detectiveCtrl;
        this.maidCtrl = maidCtrl;
        this.roomCtrl = roomCtrl;

        //our view should also implement Observer Interfaces if it needs data
        //from a model
        initComponents();
        addComponentListener(this);
        setFocusable(true);
    }

    @Override
    public void componentHidden(ComponentEvent e) 
    {

    }
    
    @Override
    public void componentMoved(ComponentEvent e) 
    {

    }
    
    @Override
    public void componentResized(ComponentEvent e)
    {

    }

    @Override
    public void componentShown(ComponentEvent e)
    {
        requestFocusInWindow();
    }

    @Override
    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        
        Graphics2D g2 = (Graphics2D) g;
        
        detectiveCtrl.draw(g2);
        maidCtrl.draw(g2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setName("MaidRoom"); // NOI18N
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 231, -1, -1));

        jLabel1.setText("MaidRoom");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 124, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        mainCtrl.showPanel("ButlerRoom");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here: 
        
        detectiveCtrl.keyPressed(evt);
        repaint();
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
        
        detectiveCtrl.keyReleased(evt);
        repaint();
    }//GEN-LAST:event_formKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
