/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_project.View;

import gui_project.ModelController.BaseModel;
import gui_project.ModelController.DetectiveController;
import gui_project.ModelController.MainController;
import gui_project.ModelController.NPCController;
import gui_project.ModelController.RoomButlerController;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import gui_project.ModelController.BaseObserver;
import gui_project.ModelController.Hint;
import gui_project.ModelController.HintController;
import gui_project.ModelController.KeyPassword;
import gui_project.ModelController.KeyPasswordController;
import gui_project.ModelController.NPC;

/**
 *
 * @author pc
 */
public class RoomButlerView extends javax.swing.JPanel implements
        ComponentListener, BaseObserver
{

    private final MainController mainCtrl;
    private final DetectiveController detectiveCtrl;
    private final NPCController assistantCtrl;
    private final RoomButlerController roomCtrl;
    private KeyPasswordController keyPasswordCtrl;
    private Rectangle keyPasswordBound;

    /**
     * Creates new form RoomView
     */
    public RoomButlerView(MainController mainCtrl,
            DetectiveController detectiveCtrl,
            NPCController assistantCtrl,
            RoomButlerController roomCtrl)
    {
        this.mainCtrl = mainCtrl;
        this.detectiveCtrl = detectiveCtrl;
        this.assistantCtrl = assistantCtrl;
        this.roomCtrl = roomCtrl;

        assistantCtrl.getNPC().registerObserver(this);
        initComponents();
        addComponentListener(this);
        setFocusable(true);
    }

    @Override
    public void update(BaseModel model)
    {
        if (model instanceof NPC)
        {
            gameTextArea.setText(((NPC) model).getSpokenLine());
        } 
        else if (model instanceof Hint)
        {
            gameTextArea.setText(((Hint) model).getMessage());
        }
        else if(model instanceof KeyPassword)
        {
            gameTextArea.setText(((KeyPassword) model).getMessage());
        }
        
        mainCtrl.updateConversationLevel();
    }

    @Override
    public void componentShown(ComponentEvent e)
    {
        roomCtrl.getItemBlockCtrls().forEach(i ->
        {
            i.getItemBlock().registerObserver(this);
        });
        
        requestFocusInWindow();
    }

    public Rectangle getBound()
    {
        return new Rectangle(10, 15,
                this.getSize().width - 30, this.getSize().height - 30);
    }

    @Override
    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);

        Graphics2D g2 = (Graphics2D) g;
        detectiveCtrl.draw(g2);
        g2.draw(getBound());

        roomCtrl.getItemBlockCtrls().forEach(itemBlockCtrl ->
        {
            if (itemBlockCtrl instanceof NPCController)
            {
                NPCController npc = (NPCController) itemBlockCtrl;
                npc.draw(g2);
            } 
            else if (itemBlockCtrl instanceof HintController)
            {
                HintController hint = (HintController) itemBlockCtrl;
                hint.draw(g2);
            }
            else if (itemBlockCtrl instanceof KeyPasswordController)
            {
                KeyPasswordController keyPassword = (KeyPasswordController) itemBlockCtrl;
                keyPassword.draw(g2);
                
                keyPasswordCtrl = keyPassword;
                keyPasswordBound = keyPassword.getView().getBound();
            }
            else
            {
                itemBlockCtrl.draw(g2);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        houseDoor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gameTextArea = new javax.swing.JTextArea();
        bedLabel = new javax.swing.JLabel();

        setName("ButlerRoom"); // NOI18N
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jLabel1.setText("ButlerRoom");

        houseDoor.setText("*");
        houseDoor.setFocusCycleRoot(true);
        houseDoor.setName("MaidRoomDoor"); // NOI18N

        gameTextArea.setColumns(20);
        gameTextArea.setRows(5);
        jScrollPane1.setViewportView(gameTextArea);

        bedLabel.setText("BED");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(249, 249, 249)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(bedLabel)
                                .addGap(230, 230, 230)
                                .addComponent(houseDoor)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 18, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(houseDoor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(bedLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

        roomCtrl.checkCollisions(evt.getKeyCode(), roomCtrl.getItemBlockCtrls(),
                detectiveCtrl, getBound());

        repaint();
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased

        detectiveCtrl.keyReleased(evt);

        if (detectiveCtrl.getView().getBound().intersects(houseDoor.getBounds()))
        {
            mainCtrl.showPanel("House");
            detectiveCtrl.setLocationX(detectiveCtrl.getDetective().getRoomHouseLocationX());
            detectiveCtrl.setLocationY(detectiveCtrl.getDetective().getRoomHouseLocationY());
        }
        else if(detectiveCtrl.getView().getBound().intersects(keyPasswordBound) &&
                !keyPasswordCtrl.getKeyPassword().isCorrect())
        {
            mainCtrl.showPanel("TailDogHouse");
        }

        repaint();
    }//GEN-LAST:event_formKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bedLabel;
    private javax.swing.JTextArea gameTextArea;
    private javax.swing.JLabel houseDoor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void componentHidden(ComponentEvent e)
    {

    }

    @Override
    public void componentMoved(ComponentEvent e)
    {

    }

    @Override
    public void componentResized(ComponentEvent e)
    {

    }
}
