/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_project.View;

import gui_project.ModelController.BaseModel;
import gui_project.ModelController.BaseObserver;
import gui_project.ModelController.DetectiveController;
import gui_project.ModelController.Hint;
import gui_project.ModelController.HintController;
import gui_project.ModelController.MainController;
import gui_project.ModelController.NPC;
import gui_project.ModelController.NPCController;
import gui_project.ModelController.RoomWifeController;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;

/**
 *
 * @author pc
 */
public class RoomWifeView extends javax.swing.JPanel implements
        ComponentListener, BaseObserver
{

    private final MainController mainCtrl;
    private final DetectiveController detectiveCtrl;
    private final RoomWifeController roomCtrl;

    /**
     * Creates new form RoomView
     */
    public RoomWifeView(MainController mainCtrl,
            DetectiveController detectiveCtrl,
            RoomWifeController roomCtrl)
    {
        this.mainCtrl = mainCtrl;
        this.detectiveCtrl = detectiveCtrl;
        this.roomCtrl = roomCtrl;

        initComponents();
        gameTextArea.setEditable(false);
        gameTextArea.setFocusable(false);
        addComponentListener(this);
        setFocusable(true);
    }

    @Override
    public void update(BaseModel model)
    {
        if (model instanceof NPC)
        {
            gameTextArea.setText(((NPC) model).getSpokenLine());
        } else if (model instanceof Hint)
        {
            gameTextArea.setText(((Hint) model).getMessage());
        }

    }

    @Override
    public void componentShown(ComponentEvent e)
    {
        roomCtrl.getItemBlockCtrls().forEach(i
                -> i.getItemBlock().registerObserver(this));
        requestFocusInWindow();
    }

    public Rectangle getBound()
    {
        return new Rectangle(10, 15,
                this.getSize().width - 30, this.getSize().height - 30);
    }

    @Override
    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);

        Graphics2D g2 = (Graphics2D) g;

        detectiveCtrl.draw(g2);
        g2.draw(getBound());

        roomCtrl.getItemBlockCtrls().forEach(itemBlockCtrl
                -> itemBlockCtrl.draw(g2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        houseDoor = new javax.swing.JLabel();
        bedLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gameTextArea = new javax.swing.JTextArea();

        setName("WifeRoom"); // NOI18N
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jLabel1.setText("WifeRoom");

        houseDoor.setText("*");
        houseDoor.setFocusCycleRoot(true);
        houseDoor.setName("MaidRoomDoor"); // NOI18N

        bedLabel.setText("BED");

        gameTextArea.setColumns(20);
        gameTextArea.setRows(5);
        jScrollPane1.setViewportView(gameTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(bedLabel)
                .addGap(236, 236, 236)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(houseDoor)))
                .addContainerGap(371, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(houseDoor))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(bedLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:

        roomCtrl.checkCollisions(evt.getKeyCode(), mainCtrl,
                detectiveCtrl, getBound());
        repaint();
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased

        detectiveCtrl.keyReleased(evt);

        if (detectiveCtrl.getView().getBound().intersects(houseDoor.getBounds()))
        {
            mainCtrl.showPanel("House");
            detectiveCtrl.setLocationX(detectiveCtrl.getDetective().getRoomHouseLocationX());
            detectiveCtrl.setLocationY(detectiveCtrl.getDetective().getRoomHouseLocationY());
        }
        repaint();
    }//GEN-LAST:event_formKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bedLabel;
    private javax.swing.JTextArea gameTextArea;
    private javax.swing.JLabel houseDoor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void componentResized(ComponentEvent e)
    {

    }

    @Override
    public void componentMoved(ComponentEvent e)
    {

    }

    @Override
    public void componentHidden(ComponentEvent e)
    {

    }

}
