/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_project.View;

import gui_project.ModelController.*;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;

/**
 *
 * @author Angelo
 */
public class RoomHouseView extends javax.swing.JPanel implements
        ComponentListener, BaseObserver
{

    private final MainController mainCtrl;
    private final DetectiveController detectiveCtrl;
    private final RoomHouseController roomCtrl;
    private final KeyPasswordController keyPasswordCtrl;

    public RoomHouseView(MainController mainCtrl,
            DetectiveController detectiveCtrl,
            RoomHouseController roomCtrl,
            KeyPasswordController keyPasswordCtrl)
    {
        this.mainCtrl = mainCtrl;
        this.detectiveCtrl = detectiveCtrl;
        this.roomCtrl = roomCtrl;
        this.keyPasswordCtrl = keyPasswordCtrl;

        initComponents();
        gameTextArea.setEditable(false);
        gameTextArea.setFocusable(false);
        addComponentListener(this);
        setFocusable(true);
    }

    @Override
    public void update(BaseModel model)
    {
        if (model instanceof Hint)
        {
            gameTextArea.setText(((Hint) model).getMessage());
        } 
        else if (model instanceof KeyPassword)
        {
            gameTextArea.setText(((KeyPassword) model).getMessage());
        }
    }

    @Override
    public void componentShown(ComponentEvent e)
    {
        roomCtrl.getItemBlockCtrls().forEach(i
                -> i.getItemBlock().registerObserver(this));

        requestFocusInWindow();
    }

    public Rectangle getBound()
    {
        return new Rectangle(10, 15,
                this.getSize().width - 30, this.getSize().height - 30);
    }

    @Override
    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);

        Graphics2D g2 = (Graphics2D) g;
        detectiveCtrl.draw(g2);
        g2.draw(getBound());

        roomCtrl.getItemBlockCtrls().forEach(itemBlockCtrl
                -> itemBlockCtrl.draw(g2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        groundDoor = new javax.swing.JLabel();
        maidRoomDoor = new javax.swing.JLabel();
        butlerRoomDoor = new javax.swing.JLabel();
        wifeRoomDoor = new javax.swing.JLabel();
        workingRoomDoor = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPanel = new javax.swing.JScrollPane();
        gameTextArea = new javax.swing.JTextArea();
        workingRoomLabel = new javax.swing.JLabel();
        maidRoomLabel = new javax.swing.JLabel();
        wifeRoomLabel = new javax.swing.JLabel();
        butlerRoomLabel = new javax.swing.JLabel();

        setName("House"); // NOI18N
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("House");
        jLabel1.setName("HouseLabel"); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 60, 40));

        groundDoor.setText("*");
        groundDoor.setFocusCycleRoot(true);
        groundDoor.setName("GroundDoor"); // NOI18N
        add(groundDoor, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 10, -1));

        maidRoomDoor.setText("*");
        maidRoomDoor.setFocusCycleRoot(true);
        maidRoomDoor.setName("MaidRoomDoor"); // NOI18N
        add(maidRoomDoor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 10, -1));

        butlerRoomDoor.setText("*");
        butlerRoomDoor.setName("ButlerRoomDoor"); // NOI18N
        add(butlerRoomDoor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 10, -1));

        wifeRoomDoor.setText("*");
        wifeRoomDoor.setName("WifeRoomDoor"); // NOI18N
        add(wifeRoomDoor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 10, -1));

        workingRoomDoor.setText("*");
        add(workingRoomDoor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 10, -1));

        jLabel2.setText("Kitchen");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, -1, -1));

        gameTextArea.setColumns(20);
        gameTextArea.setRows(5);
        jScrollPanel.setViewportView(gameTextArea);

        add(jScrollPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 380, 270, -1));

        workingRoomLabel.setText("Working Room");
        add(workingRoomLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, -1, -1));

        maidRoomLabel.setText("Maid Room");
        add(maidRoomLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        wifeRoomLabel.setText("Wife Room");
        add(wifeRoomLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        butlerRoomLabel.setText("Butler Room");
        add(butlerRoomLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_formKeyPressed
    {//GEN-HEADEREND:event_formKeyPressed

        roomCtrl.checkCollisions(evt.getKeyCode(), mainCtrl,
                detectiveCtrl, getBound());

        //check if the player wants to access a room
        if (detectiveCtrl.getView().getBound().intersects(groundDoor.getBounds()))
        {
            mainCtrl.showPanel("Ground");
            detectiveCtrl.updateGroundHouseLocation();
        } 
        else if (detectiveCtrl.getView().getBound().intersects(maidRoomDoor.getBounds()))
        {
            mainCtrl.showPanel("MaidRoom");
            detectiveCtrl.saveHouseLocation(groundDoor.getX() + 5, groundDoor.getY());

        } 
        else if (detectiveCtrl.getView().getBound().intersects(butlerRoomDoor.getBounds()))
        {
            mainCtrl.showPanel("ButlerRoom");
            detectiveCtrl.saveHouseLocation(groundDoor.getX() + 5, groundDoor.getY());
        }
        else if (detectiveCtrl.getView().getBound().intersects(wifeRoomDoor.getBounds()))
        {
            mainCtrl.showPanel("WifeRoom");
            detectiveCtrl.saveHouseLocation(groundDoor.getX() + 5, groundDoor.getY());
        }
        else if (detectiveCtrl.getView().getBound().intersects(workingRoomDoor.getBounds()))
        {
            mainCtrl.showPanel("WorkingRoom");
            detectiveCtrl.saveHouseLocation(groundDoor.getX() + 5, groundDoor.getY());
        }

        repaint();
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_formKeyReleased
    {//GEN-HEADEREND:event_formKeyReleased

        //I think we can check for the boundaries here -- if going outside the bounds
        //we wont call the keyPress
        detectiveCtrl.keyReleased(evt);
        Rectangle keyPasswordBound = keyPasswordCtrl.getView().getBound();

        if (detectiveCtrl.getView().getBound().intersects(keyPasswordBound)
                && !keyPasswordCtrl.getKeyPassword().isCorrect())
        {
            mainCtrl.showPanel("HeadOffice");
        }

        repaint();
    }//GEN-LAST:event_formKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel butlerRoomDoor;
    private javax.swing.JLabel butlerRoomLabel;
    private javax.swing.JTextArea gameTextArea;
    private javax.swing.JLabel groundDoor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPanel;
    private javax.swing.JLabel maidRoomDoor;
    private javax.swing.JLabel maidRoomLabel;
    private javax.swing.JLabel wifeRoomDoor;
    private javax.swing.JLabel wifeRoomLabel;
    private javax.swing.JLabel workingRoomDoor;
    private javax.swing.JLabel workingRoomLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void componentHidden(ComponentEvent e)
    {

    }

    @Override
    public void componentMoved(ComponentEvent e)
    {

    }

    @Override
    public void componentResized(ComponentEvent e)
    {

    }
}
