package gui_project.View;

import gui_project.ModelController.BaseModel;
import gui_project.ModelController.BaseObserver;
import gui_project.ModelController.DetectiveController;
import gui_project.ModelController.Hint;
import gui_project.ModelController.KeyPassword;
import gui_project.ModelController.KeyPasswordController;
import gui_project.ModelController.LockedAreaController;
import gui_project.ModelController.MainController;
import gui_project.ModelController.NPC;
import gui_project.ModelController.RoomWorkingController;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;

public class RoomWorkingView extends javax.swing.JPanel implements
        ComponentListener, BaseObserver
{

    private final MainController mainCtrl;
    private final DetectiveController detectiveCtrl;
    private final RoomWorkingController roomCtrl;
    private final KeyPasswordController keyPasswordCtrl;
    private final LockedAreaController lockedAreaCtrl;

    public RoomWorkingView(MainController mainCtrl,
            DetectiveController detectiveCtrl,
            RoomWorkingController roomCtrl,
            KeyPasswordController keyPasswordCtrl,
            LockedAreaController lockedAreaCtrl)
    {
        this.mainCtrl = mainCtrl;
        this.detectiveCtrl = detectiveCtrl;
        this.roomCtrl = roomCtrl;
        this.keyPasswordCtrl = keyPasswordCtrl;
        this.lockedAreaCtrl = lockedAreaCtrl;

        initComponents();
        gameTextArea.setEditable(false);
        gameTextArea.setFocusable(false);
        addComponentListener(this);
        roomCtrl.getItemBlockCtrls().forEach(i
                -> i.getItemBlock().registerObserver(this));
        setFocusable(true);
    }

    @Override
    public void update(BaseModel model)
    {
        if (model instanceof NPC)
        {
            gameTextArea.setText(((NPC) model).getSpokenLine());
        } else if (model instanceof Hint)
        {
            gameTextArea.setText(((Hint) model).getMessage());
        } else if (model instanceof KeyPassword)
        {
            gameTextArea.setText(((KeyPassword) model).getMessage());
        }
    }

    @Override
    public void componentShown(ComponentEvent e)
    {
        requestFocusInWindow();
    }

    public Rectangle getBound()
    {
        return new Rectangle(10, 15,
                this.getSize().width - 30, this.getSize().height - 30);
    }

    @Override
    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g;

        detectiveCtrl.draw(g2);
        g2.draw(getBound());

        roomCtrl.getItemBlockCtrls().forEach(itemBlockCtrl
                -> itemBlockCtrl.draw(g2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        houseDoor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gameTextArea = new javax.swing.JTextArea();

        setName("WorkingRoom"); // NOI18N
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Working Room");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        houseDoor.setText("*");
        houseDoor.setFocusCycleRoot(true);
        houseDoor.setName("MaidRoomDoor"); // NOI18N
        add(houseDoor, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, 10));

        gameTextArea.setColumns(20);
        gameTextArea.setRows(5);
        jScrollPane1.setViewportView(gameTextArea);
        gameTextArea.setFont(new java.awt.Font("Monospaced", 0, 14));

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 330, 110));
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

        roomCtrl.checkCollisions(evt.getKeyCode(), mainCtrl,
                detectiveCtrl, getBound());

        repaint();
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased

        detectiveCtrl.keyReleased(evt);
        Rectangle officeLockBound = lockedAreaCtrl.getView().getBound();
        Rectangle keyPasswordBound = keyPasswordCtrl.getView().getBound();

        if (detectiveCtrl.getView().getBound().intersects(houseDoor.getBounds()))
        {
            mainCtrl.showPanel("House");
            detectiveCtrl.setLocationX(detectiveCtrl.getDetective().getRoomHouseLocationX());
            detectiveCtrl.setLocationY(detectiveCtrl.getDetective().getRoomHouseLocationY());
        } else if (detectiveCtrl.getView().getBound().intersects(officeLockBound)
                && !lockedAreaCtrl.getLockedArea().isUnlocked())
        {
            mainCtrl.showPanel("OfficeLock");
        }
        if (detectiveCtrl.getView().getBound().intersects(keyPasswordBound)
                && !keyPasswordCtrl.getKeyPassword().isCorrect())
        {
            mainCtrl.showPanel("HeadDogHouse");
        }

        repaint();
    }//GEN-LAST:event_formKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea gameTextArea;
    private javax.swing.JLabel houseDoor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void componentResized(ComponentEvent e)
    {

    }

    @Override
    public void componentMoved(ComponentEvent e)
    {

    }

    @Override
    public void componentHidden(ComponentEvent e)
    {

    }
}
