/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_project.View;

import gui_project.ModelController.DetectiveController;
import gui_project.ModelController.ItemBlockController;
import gui_project.ModelController.MainController;
import gui_project.ModelController.NPCController;
import gui_project.ModelController.RoomWifeController;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;

/**
 *
 * @author pc
 */
public class RoomWifeView extends javax.swing.JPanel implements ComponentListener
{
    private final MainController mainCtrl;
    private final DetectiveController detectiveCtrl;
    private final NPCController wifeCtrl;
    private final NPCController daughterCtrl;
    private final RoomWifeController roomCtrl;

    /**
     * Creates new form RoomView
     */
    public RoomWifeView(MainController mainCtrl,
            DetectiveController detectiveCtrl,
            NPCController wifeCtrl,
            NPCController daughterCtrl,
            RoomWifeController roomCtrl)
    {     
        this.mainCtrl = mainCtrl;
        this.daughterCtrl = daughterCtrl;
        this.detectiveCtrl = detectiveCtrl;
        this.wifeCtrl = wifeCtrl;
        this.roomCtrl = roomCtrl;
        
        initComponents();
        addComponentListener(this);
        setFocusable(true);
    }

    @Override
    public void componentShown(ComponentEvent e)
    {
        /*we can use this method to setup the view before it is shown in the main panel
        *the requestFocus is the one used to keep the detective moving
        */
       requestFocusInWindow();
    }

    @Override
    public void componentHidden(ComponentEvent e)
    {
        /*
        we can use this to set up things before the view gets off screen
        -- I'm thinking like saving the detective's last location before leaving
        this room - so when he comes back, we can set his correct location on
        componentShown
        */
        
    }

    @Override
    public void componentResized(ComponentEvent e)
    {
        
    }

    @Override
    public void componentMoved(ComponentEvent e)
    {
       
    }
        
    public Rectangle getBound()
    {
        return new Rectangle(10, 15, 
                this.getSize().width - 30, this.getSize().height - 30);
    }
    
    @Override
    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        
        Graphics2D g2 = (Graphics2D) g;
        
        detectiveCtrl.draw(g2);
        wifeCtrl.draw(g2);
        daughterCtrl.draw(g2);
        
        g2.draw(getBound());
        
        for(ItemBlockController itemBlockCtrl : roomCtrl.getItemBlockCtrls())
        {
            itemBlockCtrl.draw(g2);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        houseDoor = new javax.swing.JLabel();

        setName("WifeRoom"); // NOI18N
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jLabel1.setText("WifeRoom");

        houseDoor.setText("*");
        houseDoor.setFocusCycleRoot(true);
        houseDoor.setName("MaidRoomDoor"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(houseDoor)))
                .addContainerGap(386, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(houseDoor)
                .addContainerGap(369, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        
        roomCtrl.checkCollisions(evt.getKeyCode(), roomCtrl.getItemBlockCtrls(), 
                detectiveCtrl, getBound());
        
        repaint();
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
        
        detectiveCtrl.keyReleased(evt);
        
        if(detectiveCtrl.getView().getBound().intersects(houseDoor.getBounds()))
        {
            mainCtrl.showPanel("House");
            detectiveCtrl.setLocationX(detectiveCtrl.getDetective().getRoomHouseLocationX());
            detectiveCtrl.setLocationY(detectiveCtrl.getDetective().getRoomHouseLocationY());
        }
        
        repaint();
    }//GEN-LAST:event_formKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel houseDoor;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}