/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_project.View;

import gui_project.ModelController.DetectiveController;
import gui_project.ModelController.ItemBlock;
import gui_project.ModelController.ItemBlockController;
import gui_project.ModelController.MainController;
import gui_project.ModelController.NPCController;
import gui_project.ModelController.RoomGroundController;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import javax.swing.ImageIcon;

/**
 *
 * @author Angelo
 */
public class RoomGroundView extends javax.swing.JPanel implements ComponentListener
{
    int checkCollision = 0;
    private int housePositionX;
    private int housePositionY;
    private final MainController mainCtrl;
    private final DetectiveController detectiveCtrl;
    private final NPCController butlerCtrl;
    private final RoomGroundController roomCtrl;

    /**
     * Creates new form RoomView
     */
    public RoomGroundView(MainController mainCtrl,
            DetectiveController detectiveCtrl,
            NPCController butlerCtrl,
            RoomGroundController roomCtrl)
    {     
        this.mainCtrl = mainCtrl;
        this.detectiveCtrl = detectiveCtrl;
        this.butlerCtrl = butlerCtrl;
        this.roomCtrl = roomCtrl;
        
        initComponents();
        addComponentListener(this);
        setFocusable(true);
    }

    @Override
    public void componentShown(ComponentEvent e)
    {
        /*we can use this method to setup the view before it is shown in the main panel
        *the requestFocus is the one used to keep the detective moving
        */
        requestFocusInWindow();
    }

    @Override
    public void componentHidden(ComponentEvent e)
    {
        /*
        we can use this to set up things before the view gets off screen
        -- I'm thinking like saving the detective's last location before leaving
        this room - so when he comes back, we can set his correct location on
        componentShown
        */
        
    }

    @Override
    public void componentResized(ComponentEvent e)
    {
        
    }

    @Override
    public void componentMoved(ComponentEvent e)
    {
       
    }
    
    public Rectangle getBound()
    {
        return new Rectangle(10, 15, 
                this.getSize().width - 30, this.getSize().height - 30);
    }
    
    public Image getHouseImage()
    {
        ImageIcon imageIcon = new ImageIcon("./Images/House.png");
        Image image = imageIcon.getImage();
        Image changeImageSize = image.getScaledInstance(200, 200, 4);
        imageIcon = new ImageIcon(changeImageSize);
        image = imageIcon.getImage();
        
        return image;
    }
    
    //This method has not been used anywhere
//    public Rectangle getHouseImageBound()
//    {
//        return new Rectangle(housePositionX, housePositionY, 
//                getHouseImage().getWidth(null), getHouseImage().getHeight(null));
//    }
    
    @Override
    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        
        Graphics2D g2 = (Graphics2D) g;
        
        detectiveCtrl.draw(g2);
        butlerCtrl.draw(g2);
        g2.draw(getBound());
        
        for(ItemBlockController itemBlockCtrl : roomCtrl.getItemBlockCtrls())
        {
            g2.draw(itemBlockCtrl.getItemBlock().getBound());
        }
        
        housePositionX = doorHouse.getLocation().x - 84;
        housePositionY = doorHouse.getLocation().y - 187;
        
        //Add houseImage as an itemBlock
        roomCtrl.addItemBlock(new ItemBlockController(new ItemBlock(housePositionX, housePositionY, 
                getHouseImage().getWidth(null), getHouseImage().getHeight(null))));
        
        g.drawImage(getHouseImage(), housePositionX, housePositionY, null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roomName = new javax.swing.JLabel();
        doorHouse = new javax.swing.JLabel();

        setName("Ground"); // NOI18N
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roomName.setText("Ground");
        add(roomName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        doorHouse.setText("_____");
        doorHouse.setName("DoorHouse"); // NOI18N
        add(doorHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_formKeyPressed
    {//GEN-HEADEREND:event_formKeyPressed
        //I think we can check for the boundaries here -- if going outside the bounds
        //we wont call the keyPress
        
        //check house collision
        roomCtrl.checkCollisions(evt.getKeyCode(), roomCtrl.getItemBlockCtrls(), 
                detectiveCtrl, getBound());
        
        repaint();
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_formKeyReleased
    {//GEN-HEADEREND:event_formKeyReleased
        //I think we can check for the boundaries here -- if going outside the bounds
        //we wont call the keyPress
        
        detectiveCtrl.keyReleased(evt);
        
        //check doorHouse collision
        if(detectiveCtrl.getView().getBound().intersects(doorHouse.getBounds()))
        {
            mainCtrl.showPanel("House");
        }
        
        repaint();
    }//GEN-LAST:event_formKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel doorHouse;
    private javax.swing.JLabel roomName;
    // End of variables declaration//GEN-END:variables
}
