package gui_project.View;

import gui_project.ModelController.BaseModel;
import gui_project.ModelController.BaseObserver;
import gui_project.ModelController.MainController;
import gui_project.ModelController.PlayerInfoController;

public class StoryPanel extends javax.swing.JPanel implements BaseObserver
{
    private MainController mainCtrl;
    private PlayerInfoController playerInfoCtrl;
    private String playerName;
    
    //todo: update player database to Player name
    public StoryPanel(MainController mainCtrl, PlayerInfoController playerInfoCtrl) 
    {
        this.playerInfoCtrl = playerInfoCtrl;
        this.mainCtrl = mainCtrl;
        initComponents();
        
        playerInfoCtrl.getPlayerInfo().registerObserver(this);
    }
    
    @Override
    public void update(BaseModel model) 
    {
        playerName = playerInfoCtrl.getPlayerInfo().getName();
        playerNameLabel.setText("Hi " + getPlayerName() + ",");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        theStoryLabel = new javax.swing.JLabel();
        playerNameLabel = new javax.swing.JLabel();
        storyLabel1 = new javax.swing.JLabel();
        storyLabel2 = new javax.swing.JLabel();
        getInfoButton = new javax.swing.JButton();

        setName("Story"); // NOI18N

        theStoryLabel.setText("THE STORY");

        playerNameLabel.setText("Hi " + playerInfoCtrl.getPlayerInfo().getName() + ",");

        storyLabel1.setText("You are a very famous detective asked");

        storyLabel2.setText("to investigate the death of a billionaire.");

        getInfoButton.setText("Get information");
        getInfoButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                getInfoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(getInfoButton)
                    .addComponent(storyLabel2)
                    .addComponent(storyLabel1)
                    .addComponent(playerNameLabel)
                    .addComponent(theStoryLabel))
                .addContainerGap(365, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(theStoryLabel)
                .addGap(29, 29, 29)
                .addComponent(playerNameLabel)
                .addGap(43, 43, 43)
                .addComponent(storyLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(storyLabel2)
                .addGap(18, 18, 18)
                .addComponent(getInfoButton)
                .addContainerGap(187, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void getInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getInfoButtonActionPerformed
        mainCtrl.showPanel("Victim");
    }//GEN-LAST:event_getInfoButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton getInfoButton;
    private javax.swing.JLabel playerNameLabel;
    private javax.swing.JLabel storyLabel1;
    private javax.swing.JLabel storyLabel2;
    private javax.swing.JLabel theStoryLabel;
    // End of variables declaration//GEN-END:variables

    //Getter
    public String getPlayerName()
    {
        return playerName;
    }  
}
